name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: push-docker-images-to-gcp
      PROJECT_ID: push-docker-images-to-gcp
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Install Python dependencies
      run: |
         make install-app-dependencies
 
    - name: Test Python App
      run: |
        make test-app

    - name: Lint Dockerfile
      run: |
        make lint-dockerfile

   - name: Build Docker Image
      run: |
        make build-docker-image

    - name: Configure Docker Client                                                                                                                           
      run: |
        make config-docker-client

    - name: Push Docker Image to Container Registry (GCR)
       env:
         GIT_TAG: v0.1.0 
         run:
           make push-docker-image-to-gcr
