name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      VERSION_TYPE: patch
      IMAGE_NAME: push-docker-images-to-gcp
      REPO_NAME: push-docker-images-to-gcp
      PROJECT_ID: push-docker-images-to-gcp
      PROJECT_LOC: europe-west1
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Install Python dependencies
      run: |
         make install-app-dependencies
 
    - name: Test Python App
      run: |
        make test-app

    - name: Lint Dockerfile
      run: |
        make lint-dockerfile

    - name: Build Docker Image
      run: |
        make build-docker-image

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        make automatic-tagging-of-releases

    - name: Configure Docker Client                                                                                                                           
      run: |
        make config-docker-client

    - name: Push Docker Image to Container Registry (GCR)
      env:
       GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run:
        make push-docker-image-to-gcr

    - name: Push Docker Image to Artifact Registry (GAR)
      env:
       GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run:
        make push-docker-image-to-gar
